version: "3.1"
services:

    frontend:
      build:
        context: .
        dockerfile: docker/frontend/Dockerfile
      container_name: mt-frontend
#      volumes:
#        - .:/home/app/money-tracker
      command: npm start
      ports:
       - "4200:4200"
